@startuml

title __METHOD's Class Diagram__\n

  namespace design.pattern.create.factory.method {
    interface design.pattern.create.factory.method.Car {
        {abstract} + name()
    }
  }
  

  namespace design.pattern.create.factory.method {
    interface design.pattern.create.factory.method.CarFactory {
        {abstract} + getCar()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.Mobai {
        + name()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.MobaiFactory {
        + getCar()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.Tesla {
        + name()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.TeslaFactory {
        + getCar()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.Test {
        {static} + main()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.Wuling {
        + name()
    }
  }
  

  namespace design.pattern.create.factory.method {
    class design.pattern.create.factory.method.WulingFactory {
        + getCar()
    }
  }
  

  design.pattern.create.factory.method.Mobai .up.|> design.pattern.create.factory.method.Car
  design.pattern.create.factory.method.MobaiFactory .up.|> design.pattern.create.factory.method.CarFactory
  design.pattern.create.factory.method.Tesla .up.|> design.pattern.create.factory.method.Car
  design.pattern.create.factory.method.TeslaFactory .up.|> design.pattern.create.factory.method.CarFactory
  design.pattern.create.factory.method.Wuling .up.|> design.pattern.create.factory.method.Car
  design.pattern.create.factory.method.WulingFactory .up.|> design.pattern.create.factory.method.CarFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
